### ISSUE TITLE
Parametrize test_espsecure.py to enable skipping unsupported signing methods (ESPTOOL-928)

### ISSUE THREAD

**Issue by befeleme** [espressif/esptool#1013]
### Operating System

Fedora Linux

### Esptool Version

4.8.0

### Python Version

Python 3.13.0~rc2

### Full Esptool Command Line that Was Run

`pytest -m host_test`

### What is the Expected Behaviour?

I want to run as much of the esptool test suite when building it for Fedora Linux, to make sure it works as expected.
ecdsa192 is not supported by openSSL in Fedora Linux, hence all the tests that operate on the key fail.
As tests are not parametrized, but rather loop over lists in the test bodies, I can't easily skip the ones I don't want to run.
Would it be possible to parametrize the tests, e.g. with the pytest `@pytest.mark.parametrize` decorator?

**Comment by radimkarnis** [comment]
Hello @befeleme,

if you want to skip certain tests, you can use the [`-k` option](https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name) of pytest to select and deselect tests based on their name.

Parametrizing the tests could be a solution, but how do we decide which criteria to parameterize? Another user could later come and say that some tests can't run on his machine because of another reason.

Do you think only the schemes (`"rsa3072", "ecdsa192", "ecdsa256", "ecdsa384"`) should be parametrized?
