### ISSUE TITLE
Question: Support for standalone app ROM

### ISSUE THREAD

**Issue by slaff** [espressif/esptool#179]
Let's say I have an application that does not need a  bootloader. I know that it is possible to write a ROM file at position 0x00 on the flash BUT is it possible with the current version to create an application and convert it to proper BIN file? The application will use the standard libmain, libphy, etc libraries coming from Espressif's SDK.

**Comment by projectgus** [comment]
The old SDKs worked this way,the ROM bootloader would boot the firmware from offset 0x0 directly instead of booting a software bootloader which then loaded the app. [elf2image --version=1](https://github.com/espressif/esptool#elf2image-for-esp8266) (the default version) creates images suitable for flashing in this way - the result is in two parts, data loaded into IRAM & DRAM goes at offset 0x0 and the data mapped to flash (IROM) is in a separate file flashed at a set offset.

Recent versions of the Espressif SDK may not support images that were created this way, it may depend on which features you use. Answering that question is outside the scope of esptool, sorry, however you may find answers at http://bbs.espressif.com/
