### ISSUE TITLE
Can't upload to ESP32 after PlartformIO (esptool) update

### ISSUE THREAD

**Issue by NRJ-Javor** [espressif/esptool#257]
I don't know if it's the right place to submit this kind of issue, I also submitted the same one in "platform-espressif32" section 6 days ago, still no reply. Anyway, I updated PlatformIO, which came with a new version of esptool. After the update, while I'm trying to upload my code to ESP32 Dev board, the following exception is thrown (here's the log of VSCode IDE):
...
Looking for upload port...
Auto-detected: COM7
Uploading .pioenvs\esp32dev\firmware.bin
usage: esptool write_flash [-h] [--flash_freq {keep,40m,26m,20m,80m}]
[--flash_mode {keep,qio,qout,dio,dout}]
[--flash_size FLASH_SIZE]
[--spi-connection SPI_CONNECTION] [--no-progress]
[--verify] [--compress | --no-compress]

[ ...] esptool write_flash: error: argument : Address "Controller" must be a number *** [upload] Error 2 ============================================================================================== [ERROR] Took 3.04 seconds ============================================================================================== The terminal process terminated with exit code: 1
The exception "esptool write_flash: error: argument: Address "Controller" must be a number" is thrown in ".platformio\packages\framework-arduinoespressif32\tools\esptool.py". Any idea how can I fix the error? I'm not familiar with either Python or esptool structure, or PlatformIO.
Any help will be kindly appreciated as my project is urgent and can't move a bit ahead...

**Comment by projectgus** [comment]
The error is being raised here:
https://github.com/espressif/esptool/blob/master/esptool.py#L2456

Because the "esptool.py write_flash" command expects a sequence of pairs of flash addresses and the filenames to flash to that address, in a sequence on the command line. Like this:
https://github.com/espressif/esptool#writing-binaries-to-flash

Seems that Platform.IO's build system (or maybe VSCode) is generating an esptool.py command line that includes the word "Controller" where a numeric address should be.

Also the fact that esptool is printing a "usage:" help statement suggests that there may be other invalid parts of the command line which is being generated.

Unfortunately you'll have to ask the Platform.IO developers about this, as it's not a problem with esptool.py itself.

If you have the .bin files building correctly with Platform.IO/VSCode, then you may find that you can flash them to the chip manually by following the steps at the link above.

Sorry I can't be of more assistance.
