### ISSUE TITLE
write_flash - digest mismatch (ESPTOOL-131)

### ISSUE THREAD

**Issue by hsiboy** [espressif/esptool#265]
wemos D1 mini pro (16M), esptool v2.2 - failed to boot after "restoring" factory firmware.

When, writing a combined image to ESP8266, verify fails, but `write_flash` doesn't catch it.

I followed the following as a test:

1. erase flash.
2. confirm flash is erased.
3. write combined image to 0x00000
4. verify image (fails).
5. read out image to diff.

First the ESP8266 is erased, using the following command:
```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 erase_flash
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 27.6s
Hard resetting...
```
The erase is verified by reading the flash to an image:
```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 read_flash 0x00000 0x400000 isitempty.img
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
4194304 (100 %)
4194304 (100 %)
Read 4194304 bytes at 0x0 in 374.9 seconds (89.5 kbit/s)...
Hard resetting...
```
This empty image is verified by eye-balling in a hex editor. all bytes are 0xFF

Next the combined image is restored:
```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 write_flash 0x00000 backup.img
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 16MB
Flash params set to 0x0290
Compressed 4194304 bytes to 205099...
Wrote 4194304 bytes (205099 compressed) at 0x00000000 in 18.0 seconds (effective 1862.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting...
```
Then the freshly written image is verified:
```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 verify_flash 0x00000 backup.img
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 16MB
Flash params set to 0x0290
Verifying 0x400000 (4194304) bytes @ 0x00000000 in flash against backup.img...
-- verify FAILED (digest mismatch)

A fatal error occurred: Verify failed.
root@9VW0BW1:~#
```
This fails despite the `write_flash` command having reported that `Hash of data verified.`

reading out the freshly written image:
```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 read_flash 0x00000 0x400000 backout.img
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
4194304 (100 %)
4194304 (100 %)
Read 4194304 bytes at 0x0 in 372.3 seconds (90.1 kbit/s)...
Hard resetting...
root@9VW0BW1:~#
```
and comparing it to the one that was written, i can see that the headers have changed. The original file header was:

```
E9 01 02 40 9C F2 10 40 00 F0 10 40 68 05 00 00
```
while what was read back out of the ESP8266 has become:

```
E9 01 02 90 9C F2 10 40 00 F0 10 40 68 05 00 00
```

why has the byte at offset 0x00000003 changed to 0x90 from 0x40?

Did esptool do this?
why didn't write_flash catch the change, it said the hash was ok?
How can i upload the combined image without esptool changing that byte?

before someone asks:

```
root@9VW0BW1:~# esptool.py --port /dev/ttyS8 flash_id
esptool.py v2.2
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
Manufacturer: ef
Device: 4018
Detected flash size: 16MB
Hard resetting...
root@9VW0BW1:~#
```

**Comment by projectgus** [comment]
Hi @hsiboy,

As of esptool.py v2.0, the default values for `-fm` and `-ff` are `keep`, so the values in the bootloader header at 0x1000 should be kept unless a different value is specified on the command line.

The default value for `-fs` is `detect`, which means esptool.py will try to detect the flash size and set the size value accordingly. This is intended to make it easier to distribute precompiled binaries (projects like MicroPython and Arduino do this) and have things "just work".

Most of this is documented in the README here:
https://github.com/espressif/esptool/#flash-modes

Although I noticed `-fs keep` is not. Will fix this.

It seems like WeMos flashed their factory bootloader with `-fs 4MB` despite having a 16MB flash chip. Which is still valid, but a little odd.

If you run `esptool.py -fs keep write_flash 0x0 my.bin` then the binary on flash will always be byte-identical to the image (even if the "real" chip size is different and possibly set to a value which will fail to work correctly on that device, ie the header says 16MB and the flash is really 4MB then usually writes after the 4MB boundary will wrap around to the beginning again.) 

I believe the bug here is that verification is failing. If you flash an image at 0x1000 (the bootloader offset) then the verification should automatically account for any changed bytes. But it seems like flashing at an earlier offset updates the header bytes but doesn't account for this when digesting. Will fix this.

**Comment by hsiboy** [comment]
Thanks for the full reply @projectgus , appreciated 👍  (btw i didn't see a tip jar anywhere).

I'll try the `-fs keep write_flash 0x0 my.bin` now, though i may poke about in the wemos image a little more, to see if i can work out the memory map. I suspect its a standard lua image.
