### ISSUE TITLE
Docs: Clarification on Value field in command response

### ISSUE THREAD

**Issue by nkolban** [espressif/esptool#287]
In this Wiki page/section:

https://github.com/espressif/esptool/wiki/Serial-Protocol#response

There is a table which shows the structure of a response message.  If we look at the table, we see a field called "Value" which is 32bits in size.  The documentation says "Response data for some operation".  Examining actual data, I seem to be finding this field is not present.  I am thinking that for those operations which don't use it, then the field is not present (and not simply unused) meaning that Data begins at offset 4 and not 8 as the table would have us believe.

If this thinking holds any merit, I'd like to suggest that we update the docs to reflect that knowledge.  When I read this section, I assume that the Value field (4 bytes) would **always** be present but only *meaningful* in a subset of cases ... as opposed to what I appear to be finding which is that it is omitted when not needed.

**Comment by projectgus** [comment]
I've modified the wiki to say "Response value used by READ_REG command (see below). Zero otherwise." for this field.

I think the confusion about offets has been resolved as well (for those following at home: the Value field is always present, it's just zero most of the time. But #294 compounds this issue of knowing what is present in the Response packet.)
