### ISSUE TITLE
Flash factory should reset boot partition

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esptool#289]
Proposal:

It would be nice that during make flash the boot partition is reset to factory.
Now it remains OTA_X if it was OTA_X

**Comment by projectgus** [comment]
Hi @Reiner1210,

I agree this would be a good option for ESP-IDF "make flash". We would need to add this information to ESP-IDF, not esptool.py, because esptool.py doesn't know anything about partitions or OTA.

I'm going to close this request, but please open it as a request on the esp-idf repo instead:
https://github.com/espressif/esp-idf/issues
