### ISSUE TITLE
esptool not connecting with ESP32S on win10 

### ISSUE THREAD

**Issue by Easydo1** [espressif/esptool#325]
* Operating system: Win 10
* Python version: 3.7
* ESP hardware in use: ESP32S

I try to connect to the ESP32 but esptool can not make a connection.
![image](https://user-images.githubusercontent.com/10611929/42136859-2d5dbb26-7d63-11e8-84f8-81b9ea84dfe6.png)

I've changed the usb cables, and tested it with an arduino and the problem is not the cable. I've connected to my new ESP32S with putty and I see this:

![image](https://user-images.githubusercontent.com/10611929/42136901-c14f1d7a-7d63-11e8-980e-24e6fe63bfb1.png)

So the board is working. 

The driver looks Oke:

![image](https://user-images.githubusercontent.com/10611929/42136929-20e59462-7d64-11e8-8efd-12d27e8b31f9.png)

I can not find any more clues on how to proceed. Is it a bug or am I forgetting something?

THX,

**Comment by projectgus** [comment]
Hi @Easydo1 ,

Do you have any more details about the dev board you're using? Does it have a way to pull IO0 low (often a button labelled BOOT or similar?) If you hold this down, does it work?

Angus

**Comment by aLoneStrider** [comment]
Hi, 
Same Problem here, working on ESP32 and getting exact same messages as @Easydo1 . @projectgus , there is no such button on the board.

**Comment by Easydo1** [comment]
@projectgus 

Here is the layout of my board.
![20180703_081040](https://user-images.githubusercontent.com/10611929/42238196-5550b4fa-7f00-11e8-93c1-ed2a612c6be9.jpg)
I've tried to flash it with pulling down the Io0 pin, meanimg pressing te button during the flashing sequens. but it did not work. Then in the process of finding the problem. I've thougt. I cant write but how about reading? The problem is that even reading the flash ID or the mac adres is not working. So the probkem must be more fundamental.

**Comment by projectgus** [comment]
Hi @Easydo1 ,

> The problem is that even reading the flash ID or the mac adres is not working. So the probkem must be more fundamental.

That's right. esptool is failing to connect to the ESP32 at all. It's trying to reset it into bootloader mode so it can talk to it, but it's failing to do so. Nothing will work if there's no communications channel to the chip.

Try running esptool while holding down the "IO0" button and then press and release the "EN" button while esptool says "Connecting..." (continuing to hold down IO0 until a connection is made). This shouldn't be necessary if the automatic reset circuit is working properly, but this looks like an older unbranded development board so it may have some hardware issues.

Hi @aLoneStrider ,

> Same Problem here, working on ESP32 and getting exact same messages as @Easydo1 . @projectgus , there is no such button on the board.

The error itself is quite generic, it means that esptool is failing to get an initial response from the ESP32. The root cause may be different or the same. I'd need more details to give any other suggestions.

Please also take a look at the Troubleshooting section of the README: https://github.com/espressif/esptool#bootloader-wont-respond

**Comment by aLoneStrider** [comment]
Hi @projectgus ,
Thanks for the reply. The problem is that I am able to flash the device without any problem on Linux (Fedora) this connection problem only happens on Windows. I checked all the points in the troubleshooting section but it's not related to any of them. 
Trace option also deployed and did not help as you can see.
![41698077-a98b59b0-7539-11e8-8854-4de7d8310e0c](https://user-images.githubusercontent.com/5527618/42250190-76d34596-7efd-11e8-8441-6db5a873df81.JPG)

**Comment by projectgus** [comment]
@aLoneStrider What hardware are you using?

**Comment by aLoneStrider** [comment]
@projectgus , ESP32 board freematics 
![f1p_3](https://user-images.githubusercontent.com/5527618/42251420-45fe1c5e-7f05-11e8-8066-318ac9f76384.jpg)

**Comment by aLoneStrider** [comment]
Update: Esptool works fine on Windows 7. The issue related only to Windows 10 probably a new security update.

**Comment by Easydo1** [comment]
@projectgus 

THX for the advice. After holding down the "IO0" button and than trying to read flash_id. It worked:

![image](https://user-images.githubusercontent.com/10611929/42289544-6d12394a-7fc0-11e8-8f27-1c1f1a6fe4fb.png)

I'll now try to flash the ESP32 with micropython

**Comment by Easydo1** [comment]
It worked thanks for the help. MicroPython v1.9.4-241 is running on t the board. TNX for the great tool

**Comment by aLoneStrider** [comment]
The issue still remains and I don't know why it is now closed. @projectgus , No suggestion from You?

**Comment by projectgus** [comment]
@aLoneStrider The issue was closed by @Easydo1 as they got their board working.

I think that despite similar symptoms the issue you're seeing is different and any fix will be different. The best thing to do is to open a new issue and provide more details there. If you can please provide the full output from `--trace` in a failing connection (rather than a screenshot of the top lines), this would be very helpful.
