### ISSUE TITLE
esptool.py: command not found

### ISSUE THREAD

**Issue by gitAnuj1234** [espressif/esptool#343]
I am trying to flash a file to esp8266 using esptool but i am again agaiin facing the same error "esptool.py: command not found". I have both python 3.6.4 and python 2.7 installed in my ubuntu 18.04.1 LTS and i am using pip install esptool to install it.
![screenshot from 2018-08-05 23-50-48](https://user-images.githubusercontent.com/36512849/43688658-6de8f9c2-990a-11e8-9309-3b084951d01b.png)

**Comment by projectgus** [comment]
Hi @gitAnuj1234 ,

Thanks for reporting this issue. I think this might be a PATH issue with your install.

If you run "pip" as a normal user on Linux (ie `pip install esptool` rather than `sudo pip install esptool` then the esptool.py executable is installed to the directory `~/local/.bin` directory (ie the hidden `.local/bin` directory inside your home directory).

In a default Ubuntu install, this directory is normally part of your user's PATH (there's a line in .profile which adds it).  Maybe the .profile file or the PATH has been modified on your install.

Some workarounds, either of which should which should work:

* Run esptool.py as `~/.local/bin/esptool.py -p /dev/ttyUSB0 ...`
* Edit the `.profile` file in your home directory and look for a line like this:
```
# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```
   ... and add it if it's not already there (note you have to log out of your session and back in before changes to .profile take effect).

**Comment by gitAnuj1234** [comment]
thanks @projectgus  for the help I used sudo pip install esptool instead of pip install esptool as advised by you and it worked ....thanks for the help

**Comment by projectgus** [comment]
Great to hear @gitAnuj1234, thanks for the update.
