### ISSUE TITLE
Wrong MAC address on ESP8285

### ISSUE THREAD

**Issue by CaptainMiddle** [espressif/esptool#362]
* Operating system: Windows 10
* Python version: 3.6
* ESP hardware in use: ESP8285

# Full esptool.py command line as run:
esptool.py --port COM5 write_flash --flash_mode dout --flash_freq 40m --flash_size 8MB 0 esp8266_at_bin_v1.5.1\ESP8266_AT_Bin_V1.5.1\bin\boot_v1.7.bin 0x01000 esp8266_at_bin_v1.5.1\ESP8266_AT_Bin_V1.5.1\bin\at\512+512\user1.1024.new.2.bin 0xfc000 esp8266_at_bin_v1.5.1\ESP8266_AT_Bin_V1.5.1\bin\esp_init_data_default.bin 0x7e000 esp8266_at_bin_v1.5.1\ESP8266_AT_Bin_V1.5.1\bin\blank.bin 0xfe000 esp8266_at_bin_v1.5.1\ESP8266_AT_Bin_V1.5.1\bin\blank.bin

# Full output from esptool.py (please copy and paste all lines of output)

> esptool.py v2.5.0
> Serial port COM5
> Connecting....
> Detecting chip type... ESP8266
> Chip is ESP8285
> Features: WiFi, Embedded Flash
> MAC: 60:01:94:87:AB:20
> Uploading stub...
> Running stub...
> Stub running...
> Configuring flash size...
> Flash params set to 0x0380
> Compressed 4080 bytes to 2936...
> Wrote 4080 bytes (2936 compressed) at 0x00000000 in 0.3 seconds (effective 114.3 kbit/s)...
> Hash of data verified.
> Compressed 427044 bytes to 305765...
> Wrote 427044 bytes (305765 compressed) at 0x00001000 in 27.5 seconds (effective 124.1 kbit/s)...
> Hash of data verified.
> Compressed 128 bytes to 75...
> Wrote 128 bytes (75 compressed) at 0x000fc000 in 0.0 seconds (effective 46.3 kbit/s)...
> Hash of data verified.
> Compressed 4096 bytes to 26...
> Wrote 4096 bytes (26 compressed) at 0x0007e000 in 0.0 seconds (effective 2097.1 kbit/s)...
> Hash of data verified.
> Compressed 4096 bytes to 26...
> Wrote 4096 bytes (26 compressed) at 0x000fe000 in 0.0 seconds (effective 1048.6 kbit/s)...
> Hash of data verified.
> 
> Leaving...
> Hard resetting via RTS pin...

# What is the expected behaviour?
The MAC address should be 60:01:94:87:AB:20. When I read it with the AT command : AT+CIPAPMAC_CUR? it answers back : +CIPAPMAC_CUR:"f8:ff:29:00:cc:c2"
Even if I write it, it changes it back when I try to connect to it.
The ssid is changed to. If I set the ssid and the password, it changes it back to "ESP_87AB20" and no pswd after the first connection try

**Comment by projectgus** [comment]
Hi @CaptainMiddle,

Sorry for the delayed response. This looks like a bug in the ESP8266 AT firmware that you're using, rather than esptool. esptool seems to be reading the hardware's MAC correctly.

The MAC address burned into hardware (which is read by esptool) cannot be changed. However, firmware can allow overriding this MAC with any other value, so if the AT command is reporting an incorrect value then this is probably why.

Some ideas:
* There is a newer version of the ESP8266 AT firmware (1.7.0) [available here](https://www.espressif.com/en/support/download/at).
* You can try doing `esptool.py erase_flash` before re-flashing the firmware, in case there is some other old 
data in the flash somewhere which is causing the AT firmware to read invalid data.
* If it's still not working, suggest asking for assistance on the ESP8266 forum: https://bbs.espressif.com/
