### ISSUE TITLE
esptool does not work with DevkitC

### ISSUE THREAD

**Issue by aaronleung** [espressif/esptool#387]
(Please delete any lines which don't apply.)

* Operating system: Ubuntu 14.04/Windows 10
* Python version: 2.7.14
* ESP hardware in use: ESP8266-DevkitC

esptool.py --port /dev/ttyS0 write_flash 0x0000 boot_v1.7.bin 0x01000 at/1024+1024/user1.2048.new.5.bin 0x1fc000 esp_init_data_default_v08.bin 0x1fe000 blank.bin 0xfe000 blank.bin
 
Running this command does not correctly flash the official devkit with the AT example firmware. Using the windows utility with the same binaries works.

**Comment by projectgus** [comment]
Hi @aaronleung ,

If Ubuntu is a virtual machine, this is usually caused by timing problems introduced by the VM environment.

* If possible, try sharing the DevKit C into the VM as a USB device not a serial port.
* Try holding down the BOOT button while running esptool.py, don't release it until a connection has been made.
* If neither of these suggestions help, please post the full output from esptool.py

**Comment by aaronleung** [comment]
It's not a VM. Seems like a pretty big issue that isn't worth solving. Going to be using ESP32 moving forward since it has better support, documentation and hardware. Closing the issue.

**Comment by projectgus** [comment]
@aaronleung OK, thanks for clarifying, I was confusing by the "Ubuntu/Windows" description in the issue report (could read this as a "Ubuntu on Windows")

is `--port /dev/ttyS0` the real port you were using? This is not usually a USB serial port address (it could have been a virtual serial port address, hence further assumption about VMs).

If you're happy to move to ESP32 then that's fine as well, of course.
