### ISSUE TITLE
V3.2: Python struct.error when doing `chip_id` (ESPTOOL-338)

### ISSUE THREAD

**Issue by dhalbert** [espressif/esptool#685]
Ubuntu 20.04 (also seen on Windows 10)
Python 3.8.10 (Windows 10 was using 3.9.x)

ESP32-S2
Adafruit Metro ESP32-S2 with ESP32-S2-WROVER module

```sh
$ esptool.py --port /dev/ttyACM0 chip_id
esptool.py v3.2
Serial port /dev/ttyACM0
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Traceback (most recent call last):
  File "/home/halbert/.local/bin/esptool.py", line 377, in detect_chip
    res = struct.unpack("<IBBBBBBBBI", res[:16])  # 4b flags, 1b flash_crypt_cnt, 7*1b key_purposes, 4b chip_id
struct.error: unpack requires a buffer of 16 bytes
[... further cascaded Python errors ...]
```

Does not fail immediately after a `flash_erase`, but after loading a firmware `.bin` , fails again.
Reverting to esptool.py V3.1 fixes the problem.

First reported here: https://forums.adafruit.com/viewtopic.php?f=60&t=184596

**Comment by radimkarnis** [comment]
Thank you for providing the extended log. The real issue is now clear.

The USB CDC serial console of the ESP32-S2 has some problems when the sequence of steps you've described happens. The issue is most likely on the side of the host drivers (connection fails even when the chip is manually hard-reset). This results in the 'BrokenPipeError: [Errno 32] Broken pipe'. 

This can be patched in esptool, as ESP32-S2 doesn't really need a second connection attempt. A fix is already in the works!
