### ISSUE TITLE
feature request: Please try to flash the block again if error occur

### ISSUE THREAD

**Issue by iddq** [espressif/esptool#70]
Please try to flash the block again if error occur

**Comment by projectgus** [comment]
Hi,

I'm going to close this one because I think with the flasher stub added in v1.2, it's no longer really necessary.

Most problems with bad flashes or failing flash operation seem to be serial connectivity problems, or problems with inadequate power. We can patch around these in esptool.py, but ultimately if you don't have reliable serial and power then the ESP8266/32 will never work reliably (in particular, once the WiFi stack starts up the power spikes are significantly bigger and you'll get brownouts and really weird crashes much more readily than during the flashing stage.) Reliable hardware is always going to be a prerequisite.

Angus
