### ISSUE TITLE
print "Unsupported detection protocol, switching and trying again..." in version 3.2 (ESPTOOL-387)

### ISSUE THREAD

**Issue by saturn99** [espressif/esptool#714]
### Operating System

debian

### Version

v3.2

### Python Version

python3.8

### Full Esptool Command Line that Was Run

python3.8 esptool.py chip_id

### What is the Expected Behaviour?

ali@DEB:~/app/esptool$ git checkout v3.1
Previous HEAD position was 245bcec Update version to v3.2
HEAD is now at 768fd2c Update to v3.1

ali@DEB:~/app/esptool$ python3.8 esptool.py chip_id
esptool.py v3.1
Found 2 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a8:**:**:**:**:**
Uploading stub...
Running stub...
Stub running...
Chip ID: 0x*******8
Hard resetting via RTS pin...

ali@DEB:~/app/esptool$ git checkout v3.2
Previous HEAD position was 768fd2c Update to v3.1
HEAD is now at 245bcec Update version to v3.2

ali@DEB:~/app/esptool$ python3.8 esptool.py chip_id
esptool.py v3.2
Found 2 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a8:**:**:**:**:**
Uploading stub...
Running stub...
Stub running...
Chip ID: 0x*******8
Hard resetting via RTS pin...

### More Information

in version `v3.2` i see this message

`Detecting chip type... Unsupported detection protocol, switching and trying again...`

**Comment by radimkarnis** [comment]
Hello @saturn99,

this is intentional. A new way to detect the chip has been implemented in https://github.com/espressif/esptool/commit/36b75a8d2e02addd14d6ce961e2b11d2aa9d17e4. The new detection protocol uses the output of `get_security_info` command to identify the chip, instead of reading a magic value. This allows chip detention even in secure download mode.

The ESP8266 doesn't support the `get_security_info` command so esptool falls back to reading the magic value and lets you know by printing the message. You can skip this by specifying the chip with `-c esp8266`.
