### ISSUE TITLE
ESPTOOL suggested to use --force but it's not available..?  (ESPTOOL-638)

### ISSUE THREAD

**Issue by DerPicknicker** [espressif/esptool#852]
### Operating System

macOS Ventura

### Esptool Version

4.5

### Python Version

3.10.9

### Chip Description

ESP32

### Device Description

Just the ESP32-NodeMCU no extra Hardware attached. 

### Hardware Configuration

Nothing connected

### How is Esptool Run

Mac Terminal

### Full Esptool Command Line that Was Run

esptool.py --chip esp32  --before=default_reset --after=no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 4MB 0x0 /Users/USERNAME/esp/esp-idf/examples/system/ota/simple_ota_example/build/bootloader/bootloader-reflash-digest.bin

### Esptool Output

```shell
A fatal error occurred: Secure Boot detected, writing to flash regions < 0x8000 is disabled to protect the bootloader. Use --force to override, please use with caution, otherwise it may brick your device!
```

### More Information

Hello, 

I want to refresh the Bootloader because I forgot to enable the flash encryption. I only enabled the Secureboot feature which works as expected. But to protect my keys I want to use the Flash Encryption as well. But I cannot re-flash the bootlader to enable the encryption. The Device is currently under development mode. 

Please help me to find out where my problems are located.  I cannot use the --force command because it's not available in the esptool. As you can see in the screenshot:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/64746593/222890125-fd478870-72b7-4804-a140-ce1547ad21aa.png">

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
The `--force` argument should be after `write_flash`. So please try this `esptool.py write_flash --help`.

I hope you know these pages as the best source of information:
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html

Please use https://esp32.com/ discussion how to solve certain problems.

I'm closing this because this is the issue and feature request tracker.
