### ISSUE TITLE
ESP32-C6 documentation is unclear (ESPTOOL-759)

### ISSUE THREAD

**Issue by baylf2000** [espressif/esptool#928]
### Chip Description

ESP32-C6

### More Information

The documentation page for esptool for the ESP32-C6 is contradictory. It states that GPIO8 must be unconnected or low AND must be high in order to enter the serial boot loader. It cannot be both at the same time.

From: https://docs.espressif.com/projects/esptool/en/latest/esp32c6/advanced-topics/boot-mode-selection.html

```
GPIO8[](https://docs.espressif.com/projects/esptool/en/latest/esp32c6/advanced-topics/boot-mode-selection.html#gpio8)

GPIO8 must also be either left unconnected/floating, or driven Low, in order to enter the serial bootloader.

GPIO8 must also be driven High, in order to enter the serial bootloader reliably. The strapping combination of GPIO8 = 0 and GPIO9 = 0 is invalid and will trigger unexpected behavior.

In normal boot mode (GPIO9 high), GPIO8 is ignored.
```

An urgent correction/clarification would be much appreciated as this is holding up the final sign-off on our project.

**Comment by radimkarnis** [comment]
Hi @baylf2000,
please see the ground truth information for the final sign-off:

<img width="665" alt="image" src="https://github.com/espressif/esptool/assets/57687985/433def9b-e85a-4a5e-9649-3ee71884679c">

The `GPIO8 must also be either left unconnected/floating, or driven Low, in order to enter the serial bootloader.` sentence is a leftover from documentation of older chips. Sorry for that, I will correct the docs ASAP.

**Comment by baylf2000** [comment]
@radimkarnis Much appreciated :) Thank you!

**Comment by radimkarnis** [comment]
@baylf2000 thanks for noticing this!
