### ISSUE TITLE
Esp32-c3 flashing documentation error says flash bootloader on address 0x1000 but it should be 0x0 (ESPTOOL-806)

### ISSUE THREAD

**Issue by javierckr** [espressif/esptool#953]
### Operating System

web browser

### Esptool Version

latest

### Python Version

latest

### More Information

This page https://docs.espressif.com/projects/esptool/en/latest/esp32c3/esptool/flashing-firmware.html flashes the bootloader on 0x1000 but here says that the bootloader is located at 0x0 https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/bootloader.html

**Comment by radimkarnis** [comment]
Hi @javierckr,
the page in esptool docs you refer to mentions examples of generating the flashing commands in a framework. Each user has to generate the commands himself. The examples are not meant to be taken directly from the webpage, these won't suit your specific case (you can even see `--chip esp32` is specified in the examples, that's why the offset is `0x1000`). It is just an example output, so you know what it will look like.

Anyway, I will try to correct this not to cause any more confusion. Thank you for the report.

**Comment by javierckr** [comment]
Thanks, I tried to make pull request but didn't found where is located the esp32-c3 wiki
